﻿#端口
server: 
  port: 9002
  tomcat: 
    uri-encoding: UTF-8
spring:
  thymeleaf:
    prefix: classpath:/templates
    encoding: UTF-8
#缓存
    cache: false
#  database
  datasource:
      url: jdbc:mysql://39.106.33.113:3306/jpt?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: cp9*:s.%sf
      driver-class-name: com.mysql.jdbc.Driver
#     启用控制台颜色
  output:
        ansi:
          enabled: ALWAYS
#      应对OPTIONS请求
  mvc:
    dispatch-options-request: true

feign:
  hystrix:
#  开启熔断机制，默认是开启的
    enabled: true
  httpclient:
    enabled: true
#    设置超时时间，防止首次调用出现服务宕机bug
  command:
    default:
      execution:
        isolation:
          thread:
#          单位 ms
            timeoutInMilliseconds: 1000*1000
# 日志级别
error: true
logging:
    file: CustomerClient.log
    level:
      org.client.com: debug

#分页每页默认条数设置
page:
  pageSize: 15

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params:
        count:
            countSql
  
#全局上传下载读取文件路径设置
filesPath: D:\\file\\
#全局文件格式-多个用,(英文)隔开
filesType: xlsx